<a href="https://colab.research.google.com/github/spaceo521/Data-Science-Projects/blob/main/MI_vs_CSK_2019_Week7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Imports & Load dataset

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

import warnings
warnings.filterwarnings('ignore')

#to display all rows and columns
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.expand_frame_repr', False)
pd.set_option('max_colwidth', -1)

In [ ]:
ipl_df = pd.read_csv('IPL_ball_by_ball.csv')

### Sneak peak into the data:

In [ ]:
ipl_df.head(5)

match_id  season  start_date                  venue  innings  ball                 batting_team                 bowling_team     striker  non_striker    bowler  runs_off_bat  extras  wides  noballs  byes  legbyes  penalty wicket_type player_dismissed  other_wicket_type  other_player_dismissed
0  335982    2008    2008-04-18  M Chinnaswamy Stadium  1        0.1   Kolkata Knight Riders        Royal Challengers Bangalore  SC Ganguly  BB McCullum  P Kumar   0             1      NaN    NaN      NaN    1.0     NaN       NaN         NaN             NaN                NaN                    
1  335982    2008    2008-04-18  M Chinnaswamy Stadium  2        3.1   Royal Challengers Bangalore  Kolkata Knight Riders        W Jaffer    JH Kallis    I Sharma  2             0      NaN    NaN      NaN   NaN      NaN       NaN         NaN             NaN                NaN                    
2  335982    2008    2008-04-18  M Chinnaswamy Stadium  2        3.2   Royal Challengers Bangalore  Kolkata Knight Riders        W Jaffer    JH Kallis    I Sharma  1             0      NaN    NaN      NaN   NaN      NaN       NaN         NaN             NaN                NaN                    
3  335982    2008    2008-04-18  M Chinnaswamy Stadium  2        3.3   Royal Challengers Bangalore  Kolkata Knight Riders        JH Kallis   W Jaffer     I Sharma  0             0      NaN    NaN      NaN   NaN      NaN       NaN         NaN             NaN                NaN                    
4  335982    2008    2008-04-18  M Chinnaswamy Stadium  2        3.4   Royal Challengers Bangalore  Kolkata Knight Riders        JH Kallis   W Jaffer     I Sharma  0             1      NaN    NaN      NaN    1.0     NaN       NaN         NaN             NaN                NaN

In [ ]:
ipl_df.batting_team.unique()

array(['Kolkata Knight Riders', 'Royal Challengers Bangalore',
       'Rajasthan Royals', 'Kings XI Punjab', 'Delhi Daredevils',
       'Chennai Super Kings', 'Deccan Chargers', 'Mumbai Indians',
       'Kochi Tuskers Kerala', 'Pune Warriors', 'Sunrisers Hyderabad',
       'Rising Pune Supergiants', 'Gujarat Lions',
       'Rising Pune Supergiant', 'Delhi Capitals', 'Punjab Kings'],
      dtype=object)

In [ ]:
ipl_df.innings.unique()

array([1, 2, 4, 3, 5, 6], dtype=int64)

In [ ]:
ipl_df = ipl_df[(ipl_df.innings == 1) | (ipl_df.innings == 2)]

In [ ]:
ipl_df.innings.unique()

array([1, 2], dtype=int64)

### Additional Columns:


In [ ]:
#1. total runs in each ball
#2. is there a wicket fall in that ball

In [ ]:
ipl_df['total_runs']= ipl_df.apply(lambda x: x['runs_off_bat'] + x['extras'], axis = 1)

In [ ]:
ipl_df.head(20)

match_id  season  start_date                  venue  innings  ball                 batting_team                 bowling_team     striker  non_striker      bowler  runs_off_bat  extras  wides  noballs  byes  legbyes  penalty wicket_type player_dismissed  other_wicket_type  other_player_dismissed  total_runs
0   335982    2008    2008-04-18  M Chinnaswamy Stadium  1        0.1   Kolkata Knight Riders        Royal Challengers Bangalore  SC Ganguly  BB McCullum  P Kumar     0             1      NaN    NaN      NaN    1.0     NaN       NaN         NaN             NaN                NaN                      1         
1   335982    2008    2008-04-18  M Chinnaswamy Stadium  2        3.1   Royal Challengers Bangalore  Kolkata Knight Riders        W Jaffer    JH Kallis    I Sharma    2             0      NaN    NaN      NaN   NaN      NaN       NaN         NaN             NaN                NaN                      2         
2   335982    2008    2008-04-18  M Chinnaswamy Stadium  2        3.2   Royal Challengers Bangalore  Kolkata Knight Riders        W Jaffer    JH Kallis    I Sharma    1             0      NaN    NaN      NaN   NaN      NaN       NaN         NaN             NaN                NaN                      1         
3   335982    2008    2008-04-18  M Chinnaswamy Stadium  2        3.3   Royal Challengers Bangalore  Kolkata Knight Riders        JH Kallis   W Jaffer     I Sharma    0             0      NaN    NaN      NaN   NaN      NaN       NaN         NaN             NaN                NaN                      0         
4   335982    2008    2008-04-18  M Chinnaswamy Stadium  2        3.4   Royal Challengers Bangalore  Kolkata Knight Riders        JH Kallis   W Jaffer     I Sharma    0             1      NaN    NaN      NaN    1.0     NaN       NaN         NaN             NaN                NaN                      1         
5   335982    2008    2008-04-18  M Chinnaswamy Stadium  2        3.5   Royal Challengers Bangalore  Kolkata Knight Riders        W Jaffer    JH Kallis    I Sharma    0             0      NaN    NaN      NaN   NaN      NaN       NaN         NaN             NaN                NaN                      0         
6   335982    2008    2008-04-18  M Chinnaswamy Stadium  2        3.6   Royal Challengers Bangalore  Kolkata Knight Riders        W Jaffer    JH Kallis    I Sharma    0             0      NaN    NaN      NaN   NaN      NaN       NaN         NaN             NaN                NaN                      0         
7   335982    2008    2008-04-18  M Chinnaswamy Stadium  2        4.1   Royal Challengers Bangalore  Kolkata Knight Riders        JH Kallis   W Jaffer     AB Agarkar  1             0      NaN    NaN      NaN   NaN      NaN       NaN         NaN             NaN                NaN                      1         
8   335982    2008    2008-04-18  M Chinnaswamy Stadium  2        4.2   Royal Challengers Bangalore  Kolkata Knight Riders        W Jaffer    JH Kallis    AB Agarkar  1             0      NaN    NaN      NaN   NaN      NaN       NaN         NaN             NaN                NaN                      1         
9   335982    2008    2008-04-18  M Chinnaswamy Stadium  2        4.3   Royal Challengers Bangalore  Kolkata Knight Riders        JH Kallis   W Jaffer     AB Agarkar  0             0      NaN    NaN      NaN   NaN      NaN       NaN         NaN             NaN                NaN                      0         
10  335982    2008    2008-04-18  M Chinnaswamy Stadium  2        4.4   Royal Challengers Bangalore  Kolkata Knight Riders        JH Kallis   W Jaffer     AB Agarkar  6             0      NaN    NaN      NaN   NaN      NaN       NaN         NaN             NaN                NaN                      6         
11  335982    2008    2008-04-18  M Chinnaswamy Stadium  2        4.5   Royal Challengers Bangalore  Kolkata Knight Riders        JH Kallis   W Jaffer     AB Agarkar  0             0      NaN    NaN      NaN   NaN      NaN       caught      JH Kallis       NaN

In [ ]:
type(ipl_df.player_dismissed[11])

str

In [ ]:
ipl_df['isout']= ipl_df['player_dismissed'].apply(lambda x: 1 if type(x) == type('str') else 0)

### Choose Teams:

In [ ]:
# t1 - bat first, t2 - bat second
# Ex: MI vs RCB, (match_id: 1254058)

t1= 'Mumbai Indians'
t2= 'Chennai Super Kings'

### Choose a match between these Teams:

In [ ]:
ipl_df[(ipl_df.batting_team == t1) & (ipl_df.bowling_team == t2) & (ipl_df.innings ==1)].match_id.unique()

array([ 392181,  392227,  501221,  598002,  598046,  598073,  729303,
        733995,  734045,  829729,  829817,  829823, 1136561, 1175370,
       1178419, 1181768, 1216492], dtype=int64)

In [ ]:
matchID = 1181768

In [ ]:
mdf = ipl_df[ipl_df.match_id == matchID]

In [ ]:
mdf.head(5)

match_id  season  start_date                               venue  innings  ball         batting_team    bowling_team    striker non_striker          bowler  runs_off_bat  extras  wides  noballs  byes  legbyes  penalty wicket_type player_dismissed  other_wicket_type  other_player_dismissed  total_runs  isout
178810  1181768   2019    2019-05-12  Rajiv Gandhi International Stadium  2        7.2   Chennai Super Kings  Mumbai Indians  SR Watson  SK Raina    RD Chahar       0             0      NaN    NaN      NaN   NaN      NaN       NaN         NaN             NaN                NaN                      0           0    
178811  1181768   2019    2019-05-12  Rajiv Gandhi International Stadium  2        7.1   Chennai Super Kings  Mumbai Indians  SK Raina   SR Watson   RD Chahar       1             0      NaN    NaN      NaN   NaN      NaN       NaN         NaN             NaN                NaN                      1           0    
178812  1181768   2019    2019-05-12  Rajiv Gandhi International Stadium  2        6.7   Chennai Super Kings  Mumbai Indians  SR Watson  SK Raina    MJ McClenaghan  0             0      NaN    NaN      NaN   NaN      NaN       NaN         NaN             NaN                NaN                      0           0    
178813  1181768   2019    2019-05-12  Rajiv Gandhi International Stadium  2        5.6   Chennai Super Kings  Mumbai Indians  SR Watson  SK Raina    SL Malinga      4             0      NaN    NaN      NaN   NaN      NaN       NaN         NaN             NaN                NaN                      4           0    
178814  1181768   2019    2019-05-12  Rajiv Gandhi International Stadium  2        6.6   Chennai Super Kings  Mumbai Indians  SR Watson  SK Raina    MJ McClenaghan  0             0      NaN    NaN      NaN   NaN      NaN       NaN         NaN             NaN                NaN                      0           0

In [ ]:
mdf.reset_index(inplace = True, drop = True)

In [ ]:
mdf.head()

match_id  season  start_date                               venue  innings  ball         batting_team    bowling_team    striker non_striker          bowler  runs_off_bat  extras  wides  noballs  byes  legbyes  penalty wicket_type player_dismissed  other_wicket_type  other_player_dismissed  total_runs  isout
0  1181768   2019    2019-05-12  Rajiv Gandhi International Stadium  2        7.2   Chennai Super Kings  Mumbai Indians  SR Watson  SK Raina    RD Chahar       0             0      NaN    NaN      NaN   NaN      NaN       NaN         NaN             NaN                NaN                      0           0    
1  1181768   2019    2019-05-12  Rajiv Gandhi International Stadium  2        7.1   Chennai Super Kings  Mumbai Indians  SK Raina   SR Watson   RD Chahar       1             0      NaN    NaN      NaN   NaN      NaN       NaN         NaN             NaN                NaN                      1           0    
2  1181768   2019    2019-05-12  Rajiv Gandhi International Stadium  2        6.7   Chennai Super Kings  Mumbai Indians  SR Watson  SK Raina    MJ McClenaghan  0             0      NaN    NaN      NaN   NaN      NaN       NaN         NaN             NaN                NaN                      0           0    
3  1181768   2019    2019-05-12  Rajiv Gandhi International Stadium  2        5.6   Chennai Super Kings  Mumbai Indians  SR Watson  SK Raina    SL Malinga      4             0      NaN    NaN      NaN   NaN      NaN       NaN         NaN             NaN                NaN                      4           0    
4  1181768   2019    2019-05-12  Rajiv Gandhi International Stadium  2        6.6   Chennai Super Kings  Mumbai Indians  SR Watson  SK Raina    MJ McClenaghan  0             0      NaN    NaN      NaN   NaN      NaN       NaN         NaN             NaN                NaN                      0           0

In [ ]:
df1 = mdf[mdf.innings ==1]
df2 = mdf[mdf.innings ==2]

### Outcomes:

In [ ]:
# 0,1,2,3,4,5,6,7, 'W', 'extras'
outcomes = [0,1,2,3,4,6,'w']

In [ ]:
ipl_df[ipl_df.batting_team == t1].total_runs.value_counts()

1    10347
0    9050 
4    2932 
2    1575 
6    1270 
3    92   
5    47   
7    7    
Name: total_runs, dtype: int64

In [ ]:
ipl_df[ipl_df.batting_team == t1].isout.sum()

1237

In [ ]:
t1_outcomes_count = ipl_df[ipl_df.batting_team == t1].total_runs.value_counts()
t2_outcomes_count = ipl_df[ipl_df.batting_team == t2].total_runs.value_counts()

In [ ]:
t1_outs = ipl_df[ipl_df.batting_team == t1].isout.sum()
t2_outs = ipl_df[ipl_df.batting_team == t2].isout.sum()

In [ ]:
t1_outcomes = []
t2_outcomes = []


for outcome in outcomes:
    if outcome !='w':
        t1_outcomes.append(t1_outcomes_count[outcome])
        t2_outcomes.append(t2_outcomes_count[outcome])
    else:
        t1_outcomes.append(t1_outs)
        t2_outcomes.append(t2_outs)


In [ ]:
t1_outcomes, t2_outcomes

([9050, 10347, 1575, 92, 2932, 1270, 1237],
 [7671, 9326, 1536, 90, 2520, 1104, 952])

In [ ]:
t1_pb_outcomes = [i/sum(t1_outcomes) for i in t1_outcomes]
t2_pb_outcomes = [i/sum(t2_outcomes) for i in t2_outcomes]

In [ ]:
t1_pb_outcomes

[0.3414707768931819,
 0.3904086329849451,
 0.05942723465268083,
 0.0034713051352677055,
 0.11062898539787948,
 0.04791910349771724,
 0.046673961438327735]

In [ ]:
# (0 --> 1)
# ex:
# dot - 34%
# ones - 34% + 39% = 73%

In [ ]:
t1_pb_ls = np.cumsum(t1_pb_outcomes)
t2_pb_ls = np.cumsum(t2_pb_outcomes)

In [ ]:
t1_pb_ls, t2_pb_ls

(array([0.34147078, 0.73187941, 0.79130664, 0.79477795, 0.90540694,
        0.95332604, 1.        ]),
 array([0.3306608 , 0.73266089, 0.79887064, 0.80275012, 0.91137549,
        0.95896375, 1.        ]))

### Fetch probability values:

In [ ]:
# MI = [0.34147078, 0.73187941, 0.79130664, 0.79477795, 0.90540694,0.95332604, 1]
#CSK = [0.3306608 , 0.73266089, 0.79887064, 0.80275012, 0.91137549, 0.95896375, 1]

In [ ]:
def get_pbvalues(teamName):
    if teamName == 'MI':
        p_0 = 0.34147078
        p_1 = 0.73187941
        p_2 = 0.79130664
        p_3 = 0.79477795
        p_4 = 0.90540694
        p_6 = 0.95332604
        p_w = 1

    elif teamName == 'CSK':
        p_0 = 0.3306608
        p_1 = 0.73266089
        p_2 = 0.79887064
        p_3 = 0.80275012
        p_4 = 0.91137549
        p_6 = 0.95896375
        p_w = 1

    return p_0,p_1,p_2,p_3,p_4,p_6,p_w

### Runs prediction Model:

In [ ]:
def predict_runs(target, curr_score, curr_wickets, curr_overs):

    #pb values of both teams
    i1p_0, i1p_1, i1p_2, i1p_3, i1p_4, i1p_6, i1p_w = get_pbvalues('MI')
    i2p_0, i2p_1, i2p_2, i2p_3, i2p_4, i2p_6, i2p_w = get_pbvalues('CSK')

    pred_runs = curr_score
    pred_wks = curr_wickets
    leftover_balls = 120- curr_overs*6

    for i in range(leftover_balls):
        r_value = np.random.random()

        if r_value <= i2p_0:
            pred_runs += 0
        elif r_value <= i2p_1:
            pred_runs += 1
        elif r_value <= i2p_2:
            pred_runs += 2
        elif r_value <= i2p_3:
            pred_runs += 3
        elif r_value <= i2p_4:
            pred_runs += 4
        elif r_value <= i2p_6:
            pred_runs += 6
        else:
            pred_runs += 0
            pred_wks += 1

            if pred_wks == 10:
                break
        if pred_runs > target:
            break

            #print('pred_runs:', pred_runs)
           #print('pred_wks:', pred_wks)

    return pred_runs



In [ ]:
# predict_runs(target, curr_score, curr_wickets, curr_overs)
predict_runs(149, 0, 0, 0)

150

### Winner function:

In [ ]:
def get_win(pred_runs, target):
    if pred_runs > target:
        return 'win'
    elif pred_runs == target:
        return 'tie'
    else:
        return 'loss'


In [ ]:
#runs, wickets, overs,
# win, 1st ing score

#MI = 149/8

target = 150

curr_score = 72
curr_wickets = 2
curr_overs = 10


iter_count = 100

runs_ls = []
results_ls = []

win_count = 0
tie_count = 0
loss_count = 0

for i in range(iter_count):
    pred_runs = predict_runs(target, curr_score, curr_wickets, curr_overs)
    runs_ls.append(pred_runs)
    result_pred = get_win(pred_runs, target)
    results_ls.append(result_pred)

    if result_pred == 'win':
        win_count += 1
    elif result_pred == 'tie':
        tie_count += 1
    else:
        loss_count +=1

In [ ]:
win_count, tie_count, loss_count

(38, 3, 59)

### Find out Runs at a required stage:

In [ ]:
# find out runs:
def find_runs(curr_score, target, curr_wickets, at_overs):
    runs_ls = []
    results_ls = []

    req_runs = []
    win_ls = []

    for i in range(curr_score, target + 1):
        win_count = 0
        tie_count = 0
        loss_count = 0

        for j in range(100):
            pred_runs = predict_runs(target, i, curr_wickets, at_overs)
            runs_ls.append(pred_runs)
            result_pred = get_win(pred_runs, target)
            results_ls.append(result_pred)

            if result_pred == 'win':
                win_count += 1
            elif result_pred == 'tie':
                tie_count += 1
            else:
                loss_count +=1

            win_ls.append(win_count)
            req_runs.append(i)
            #print('runs', i, 'win%:', win_count)

    required_runs = curr_score
    for i in range(len(req_runs)):
        if win_ls[i] >= 50:
            required_runs = req_runs[i]
            #print('Runs to be:', req_runs[i])
            break

    return required_runs

In [ ]:
#find_runs(curr_score, target, curr_wickets, at_overs)
find_runs(72, 150, 2, 10 )

73

### Find out Wickets they can afford to lose:

In [ ]:
def find_wickets(curr_score, target, curr_wickets, at_overs):

#find_runs(curr_score, target, curr_wickets, at_overs)
    req_runs = find_runs(curr_score, target, curr_wickets, at_overs)

    runs_ls = []
    results_ls = []

    req_wks = []
    win_ls = []

    for i in range(curr_wickets, 10):
        win_count = 0
        tie_count = 0
        loss_count = 0

        for j in range(100):
#        pred_runs = predict_runs(target, i, curr_wickets, at_overs)
            pred_runs = predict_runs(target, curr_score, i, at_overs)
            runs_ls.append(pred_runs)
            result_pred = get_win(pred_runs, target)
            results_ls.append(result_pred)

            if result_pred == 'win':
                win_count += 1
            elif result_pred == 'tie':
                tie_count += 1
            else:
                loss_count +=1

        win_ls.append(win_count)
        req_wks.append(i)
        print('wickets', i, 'win%:', win_count)

    req_wicket_value = curr_wickets

    for i in range(len(req_wks)):
        if (win_ls[i] < 45) :
            req_wicket_value = req_wks[i]
            break

    return req_wicket_value

In [ ]:
#wickets they can afford to lose:

# find_wickets(curr_score, target, curr_wickets, at_overs)
find_wickets(72, 150, 2, 10)

wickets 2 win%: 37
wickets 3 win%: 45
wickets 4 win%: 43
wickets 5 win%: 38
wickets 6 win%: 32
wickets 7 win%: 30
wickets 8 win%: 19
wickets 9 win%: 8


2

### Function: Interactive chart

In [ ]:
%matplotlib inline
from ipywidgets import interactive
import ipywidgets as widgets
import matplotlib.pyplot as plt
import numpy as np

def find_runs_wickets(curr_wks, at_overs, target_score):
    plt.figure(figsize = (16, 4))
    # x = np.linspace(-10, 10, num=1000)
    x = np.array(list(range(21)))
    req_value = find_runs(72, target_score, curr_wks, at_overs)
    req_wk_value = find_wickets(72, target_score, curr_wks, at_overs)

    if at_overs == 10:
        req_value = 72
        req_wk_value = 2


    # print(req_value)
    y = np.array([req_value for i in range(21)])

    # plt.plot(x, current_overs * x + target_score)
    # plt.plot(x, y)
    plt.scatter(at_overs, req_value, s = 1200, color = 'red')
    plt.axhline(target_score, ls = '--', color = 'blue')
    plt.text( 1, target_score + 10, 'Target Score :' + str(target_score) , color = 'darkblue', fontsize = 13)
    plt.text( at_overs, req_value, str(req_value) + '/' + str(req_wk_value), color = 'white', fontsize = 12,  horizontalalignment='center', verticalalignment='center')
    plt.text(at_overs, req_value - 30, 'CSK has to be at ' + str(req_value) + '/' +  str(req_wk_value) + ' after ' + str(at_overs) + ' ov', horizontalalignment='center')
    plt.ylim(50, target_score + 50)
    plt.xticks(x)
    plt.title('Where should CSK be?', fontsize = 20)
    plt.xlabel('Overs')
    plt.ylabel('Score')
    plt.show()

# x=widgets.IntSlider(min=-10, max=30, step=1, value=10)

# find_wickets(curr_score, target, curr_wickets, at_overs)
# find_wickets(87, 150, 1, 14)


### Interactive Visualization

In [ ]:
print('current_score = CSK: 72/2 (10 overs)')
print('')

interactive_plot = interactive(find_runs_wickets, curr_wks = widgets.IntSlider(min=2, max = 10, step=1, value=1), at_overs=widgets.IntSlider(min=10, max=20, step=1, value=10), target_score= widgets.IntSlider(min=0, max=250, step=1, value=150))
output = interactive_plot.children[-1]
output.layout.height = '450px'
interactive_plot

current_score = CSK: 72/2 (10 overs)



interactive(children=(IntSlider(value=2, description='curr_wks', max=10, min=2), IntSlider(value=10, descripti…